### ISSUE TITLE
Add RFC numbers & links where appropriate

### ISSUE THREAD

**Issue by shane-kerr** [DNS-Resolver-BCP-TF/Resolver-Recommendations#1]

**Comment by moonshiner** [comment]
- Local root (and maybe local TLD?)
    - RFC8806
  - Verify root zone with ZONEMD
    - RFC8976
  - EDNS0 sizes to minimize fragmentation, especially for IPv6
  - Aggressive NSEC caching
    -  RFC8189
  - QNAME minimization
    - RFC7816
  - Negative trust anchors
    - RFC7646
  - TTL record pre-fetch
  - EDNS client subnet
    - RFC7871
  - DNS cookies shared secret
    - RFC7873
  - DoT
    - RFC7858
  - DoH
    - RFC8484
  - DoQ
    - RFC9250
  - Trust anchor reporting
  - DNS error reporting
    - https://datatracker.ietf.org/doc/draft-ietf-dnsop-dns-error-reporting

**Comment by shane-kerr** [comment]
I think we're good for this one. :smile:
