### ISSUE TITLE
Is RFC7766 meant here? Previously known as RFC5966?

### ISSUE THREAD

**Issue by mdavids** [DNS-Resolver-BCP-TF/Resolver-Recommendations#32]
https://github.com/DNS-Resolver-BCP-TF/Resolver-Recommendations/blob/20116ce9f82078329680b48374908220c6ce8c05/DNS-options.md?plain=1#L28 mentions RFC5996 but that seems wrong.

Is RFC7766 meant here? Or perhaps RFC5966?

**Comment by moonshiner** [comment]
Yes - this should bee 7766 instead of 5966 (which I mistyped)

**Comment by mdavids** [comment]
There is also [RFC9210](https://datatracker.ietf.org/doc/rfc9210/) that is related and perhaps relevant as well.

**Comment by shane-kerr** [comment]
I've merged #36 from @moonshiner which fixes the reference.
