### ISSUE TITLE
Is draft-vixie-dns-rpz meant here?

### ISSUE THREAD

**Issue by mdavids** [DNS-Resolver-BCP-TF/Resolver-Recommendations#33]
https://github.com/DNS-Resolver-BCP-TF/Resolver-Recommendations/blob/20116ce9f82078329680b48374908220c6ce8c05/privacy-filtering.md?plain=1#L36 mentions RFC8976 but that seems strange. Is draft-vixie-dns-rpz meant here?

**Comment by moonshiner** [comment]
Yes 

though I was sure RPZ was given an RFC number, but it has not

**Comment by shane-kerr** [comment]
I've corrected this in the pull request #39.

**Comment by moonshiner** [comment]
Merged
