### ISSUE TITLE
Include RFC9461 and RFC9462

### ISSUE THREAD

**Issue by mdavids** [DNS-Resolver-BCP-TF/Resolver-Recommendations#35]
I believe we should include [RFC9461](https://datatracker.ietf.org/doc/html/rfc9461) and [RFC9462](https://datatracker.ietf.org/doc/html/rfc9462) in the document.

**Comment by shane-kerr** [comment]
I've merged PR #36 from @moonshiner, which adds a section on DDR and references RFC 9462. RFC 9461 is referenced there, although only tangentially. Do you think that we need to explicitly include RFC 9461?

**Comment by moonshiner** [comment]
I can't see a use case for 9461, ot an explanation

**Comment by mdavids** [comment]
With regard to RFC9461, I was in doubt too, but in the Examples section (7) was some stuff that triggered me.
